Rebuild Sass node
Error message:

Error: Missing binding /Volumes/Dandy/Website/02 Website 2017
update/website-2017/node_modules/gulp-sass/node_modules/node-sass/vendor
/darwin-x64-48/binding.node
Node Sass could not find a binding for your current environment: OS X
64-bit with Node.js 6.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 4.x

This usually happens because your environment has changed since running
`npm install`.
Run `npm rebuild node-sass` to build the binding for your current
environment.